/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.interfaces.DAOBooks;
import com.mycompany.pei.sbibliotecario.DAOBooksImpl;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import com.mycompany.utils.Utils;
import javax.swing.JTextField;

/**
 *
 * @author Rawad
 */
public class UpBooks extends javax.swing.JPanel {

    boolean isEdition = false;
    com.mycompany.models.Books bookEdition;

    public UpBooks() {
        initComponents();
        InitStyles();

    }

    public UpBooks(com.mycompany.models.Books book) {
        initComponents();
        isEdition = true;
        bookEdition = book;
        InitStyles();
    }

    private void InitStyles() {
        titleTxt.putClientProperty("JTextField.placeholderText", "Ingrese el titulo del libro");
        titleTxt.setPlaceholderColor(new Color(183, 183, 183));

        dateTxt.putClientProperty("JTextField.placeholderText", "Ingrese la fecha de publicacion");
        dateTxt.setPlaceholderColor(new Color(183, 183, 183));

        authorTxt.putClientProperty("JTextField.placeholderText", "Ingrese el nombre del autor");
        authorTxt.setPlaceholderColor(new Color(183, 183, 183));

        catTxt.putClientProperty("JTextField.placeholderText", "Ingrese la categoria del libro");
        catTxt.setPlaceholderColor(new Color(183, 183, 183));

        edTxt.putClientProperty("JTextField.placeholderText", "Ingrese la edicion del libro");
        edTxt.setPlaceholderColor(new Color(183, 183, 183));

        langTxt.putClientProperty("JTextField.placeholderText", "Ingrese el idioma del libro");
        langTxt.setPlaceholderColor(new Color(183, 183, 183));

        pagsTxt.putClientProperty("JTextField.placeholderText", "Ingrese la cantidad de paginas");
        pagsTxt.setPlaceholderColor(new Color(183, 183, 183));

        descTxt.putClientProperty("JTextField.placeholderText", "Ingrese la descripcion del libro");
        descTxt.setPlaceholderColor(new Color(183, 183, 183));

        stockTxt.putClientProperty("JTextField.placeholderText", "Stock");
        stockTxt.setPlaceholderColor(new Color(183, 183, 183));

        dispTxt.putClientProperty("JTextField.placeholderText", "Disponibles");
        dispTxt.setPlaceholderColor(new Color(183, 183, 183));

        ejemTxt.putClientProperty("JTextField.placeholderText", "Ejemplares");
        ejemTxt.setPlaceholderColor(new Color(183, 183, 183));

        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                requestFocus(); // Fuerza el foco al frame principal
            }
        });

        if (isEdition) {
            Welcome.setText("Editar Libro");
            button.setText("Guardar");

            if (bookEdition != null) {
                titleTxt.setText(bookEdition.getTitle());
                dateTxt.setText(bookEdition.getDate());
                authorTxt.setText(bookEdition.getAuthor());
                catTxt.setText(bookEdition.getCategory());
                edTxt.setText(bookEdition.getEdit());
                langTxt.setText(bookEdition.getLang());
                pagsTxt.setText(bookEdition.getPages());
                descTxt.setText(bookEdition.getDescription());
                stockTxt.setText(bookEdition.getStock() + "");
                dispTxt.setText(bookEdition.getAvailable() + "");
                ejemTxt.setText(bookEdition.getEjemplares());
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        Text = new com.mycompany.components.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        titleTxt = new com.mycompany.components.RoundedTextField();
        button = new com.mycompany.components.ButtonUse();
        jLabel4 = new javax.swing.JLabel();
        dateTxt = new com.mycompany.components.RoundedTextField();
        jLabel5 = new javax.swing.JLabel();
        authorTxt = new com.mycompany.components.RoundedTextField();
        jLabel6 = new javax.swing.JLabel();
        catTxt = new com.mycompany.components.RoundedTextField();
        jLabel7 = new javax.swing.JLabel();
        edTxt = new com.mycompany.components.RoundedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        langTxt = new com.mycompany.components.RoundedTextField();
        jLabel8 = new javax.swing.JLabel();
        pagsTxt = new com.mycompany.components.RoundedTextField();
        jLabel9 = new javax.swing.JLabel();
        descTxt = new com.mycompany.components.RoundedTextField();
        jLabel10 = new javax.swing.JLabel();
        stockTxt = new com.mycompany.components.RoundedTextField();
        jLabel11 = new javax.swing.JLabel();
        ejemTxt = new com.mycompany.components.RoundedTextField();
        jLabel12 = new javax.swing.JLabel();
        dispTxt = new com.mycompany.components.RoundedTextField();

        setBackground(new Color(0,0,0,0));
        setMinimumSize(new java.awt.Dimension(774, 612));
        setPreferredSize(new java.awt.Dimension(774, 612));

        bg.setBackground(new java.awt.Color(255, 255, 255,0));
        bg.setMinimumSize(new java.awt.Dimension(774, 612));
        bg.setPreferredSize(new java.awt.Dimension(774, 612));

        Welcome.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        Welcome.setForeground(new java.awt.Color(30, 30, 30));
        Welcome.setText("Agregar Libro");

        Text.setBackground(new java.awt.Color(249, 249, 249));
        Text.setForeground(new java.awt.Color(10, 10, 10));
        Text.setRoundBottomLeft(35);
        Text.setRoundBottomRight(35);
        Text.setRoundTopLeft(35);
        Text.setRoundTopRight(35);

        jLabel2.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(10, 10, 10));
        jLabel2.setText("Titulo");

        titleTxt.setBackground(new Color(255,255,255,0));
        titleTxt.setForeground(new java.awt.Color(10, 10, 10));
        titleTxt.setBorderRadius(20);
        titleTxt.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        titleTxt.setMinimumSize(new java.awt.Dimension(645, 45));
        titleTxt.setPreferredSize(new java.awt.Dimension(645, 45));

        button.setForeground(new java.awt.Color(253, 253, 253));
        button.setText("Agregar");
        button.setColorClick(new java.awt.Color(42, 42, 42));
        button.setColorOver(new java.awt.Color(42, 42, 42));
        button.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        button.setRadius(40);
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(10, 10, 10));
        jLabel4.setText("Fecha De Publicacion");

        dateTxt.setBackground(new Color(255,255,255,0));
        dateTxt.setForeground(new java.awt.Color(10, 10, 10));
        dateTxt.setBorderRadius(20);
        dateTxt.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        dateTxt.setMinimumSize(new java.awt.Dimension(645, 45));
        dateTxt.setPreferredSize(new java.awt.Dimension(645, 45));

        jLabel5.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(10, 10, 10));
        jLabel5.setText("Autor");

        authorTxt.setBackground(new Color(255,255,255,0));
        authorTxt.setForeground(new java.awt.Color(10, 10, 10));
        authorTxt.setBorderRadius(20);
        authorTxt.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        authorTxt.setMinimumSize(new java.awt.Dimension(645, 45));
        authorTxt.setPreferredSize(new java.awt.Dimension(645, 45));

        jLabel6.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(10, 10, 10));
        jLabel6.setText("Categoria");

        catTxt.setBackground(new Color(255,255,255,0));
        catTxt.setForeground(new java.awt.Color(10, 10, 10));
        catTxt.setBorderRadius(20);
        catTxt.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        catTxt.setMinimumSize(new java.awt.Dimension(645, 45));
        catTxt.setPreferredSize(new java.awt.Dimension(645, 45));

        jLabel7.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(10, 10, 10));
        jLabel7.setText("Edicion");

        edTxt.setBackground(new Color(255,255,255,0));
        edTxt.setForeground(new java.awt.Color(10, 10, 10));
        edTxt.setBorderRadius(20);
        edTxt.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        edTxt.setMinimumSize(new java.awt.Dimension(645, 45));
        edTxt.setPreferredSize(new java.awt.Dimension(645, 45));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));

        jLabel3.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(10, 10, 10));
        jLabel3.setText("Idioma");

        langTxt.setBackground(new Color(255,255,255,0));
        langTxt.setForeground(new java.awt.Color(10, 10, 10));
        langTxt.setBorderRadius(20);
        langTxt.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        langTxt.setMinimumSize(new java.awt.Dimension(645, 45));
        langTxt.setPreferredSize(new java.awt.Dimension(645, 45));

        jLabel8.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(10, 10, 10));
        jLabel8.setText("Páginas");

        pagsTxt.setBackground(new Color(255,255,255,0));
        pagsTxt.setForeground(new java.awt.Color(10, 10, 10));
        pagsTxt.setBorderRadius(20);
        pagsTxt.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        pagsTxt.setMinimumSize(new java.awt.Dimension(645, 45));
        pagsTxt.setPreferredSize(new java.awt.Dimension(645, 45));

        jLabel9.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(10, 10, 10));
        jLabel9.setText("Descripcion");

        descTxt.setBackground(new Color(255,255,255,0));
        descTxt.setForeground(new java.awt.Color(10, 10, 10));
        descTxt.setBorderRadius(20);
        descTxt.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        descTxt.setMinimumSize(new java.awt.Dimension(645, 45));
        descTxt.setPreferredSize(new java.awt.Dimension(645, 45));

        jLabel10.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(10, 10, 10));
        jLabel10.setText("Stock");

        stockTxt.setBackground(new Color(255,255,255,0));
        stockTxt.setForeground(new java.awt.Color(10, 10, 10));
        stockTxt.setBorderRadius(20);
        stockTxt.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        stockTxt.setMinimumSize(new java.awt.Dimension(645, 45));
        stockTxt.setPreferredSize(new java.awt.Dimension(645, 45));

        jLabel11.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(10, 10, 10));
        jLabel11.setText("Ejemplares");

        ejemTxt.setBackground(new Color(255,255,255,0));
        ejemTxt.setForeground(new java.awt.Color(10, 10, 10));
        ejemTxt.setBorderRadius(20);
        ejemTxt.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        ejemTxt.setMinimumSize(new java.awt.Dimension(645, 45));
        ejemTxt.setPreferredSize(new java.awt.Dimension(645, 45));

        jLabel12.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(10, 10, 10));
        jLabel12.setText("Disponibles");

        dispTxt.setBackground(new Color(255,255,255,0));
        dispTxt.setForeground(new java.awt.Color(10, 10, 10));
        dispTxt.setBorderRadius(20);
        dispTxt.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        dispTxt.setMinimumSize(new java.awt.Dimension(645, 45));
        dispTxt.setPreferredSize(new java.awt.Dimension(645, 45));

        javax.swing.GroupLayout TextLayout = new javax.swing.GroupLayout(Text);
        Text.setLayout(TextLayout);
        TextLayout.setHorizontalGroup(
            TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TextLayout.createSequentialGroup()
                        .addGroup(TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(catTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(authorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(descTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(pagsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(langTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ejemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TextLayout.createSequentialGroup()
                                .addGroup(TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(stockTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12)
                                    .addComponent(dispTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(37, 37, 37)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        TextLayout.setVerticalGroup(
            TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(TextLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(authorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(catTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(edTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(TextLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(langTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pagsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(TextLayout.createSequentialGroup()
                                .addComponent(descTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stockTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TextLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dispTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ejemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                        .addGap(68, 68, 68))
                    .addComponent(Text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        String mtitle = titleTxt.getText();
        String date = dateTxt.getText();
        String author = authorTxt.getText();
        String cat = catTxt.getText();
        String ed = edTxt.getText();
        String lang = langTxt.getText();
        String pags = pagsTxt.getText();
        String desc = descTxt.getText();
        String stock = stockTxt.getText();
        String disp = dispTxt.getText();
        String ejem = ejemTxt.getText();

        // Validaciones para los campos
        if (mtitle.isEmpty() || date.isEmpty() || author.isEmpty() || cat.isEmpty() || ed.isEmpty()
                || lang.isEmpty() || pags.isEmpty() || desc.isEmpty() || stock.isEmpty() || disp.isEmpty() || ejem.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            titleTxt.requestFocus();
            return;
        } else if (!Utils.isNumeric(stock) || !Utils.isNumeric(disp)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Los campos Stock y Disponibles deben ser números enteros. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            titleTxt.requestFocus();
            return;
        }

        com.mycompany.models.Books book = isEdition ? bookEdition : new com.mycompany.models.Books();
        book.setTitle(mtitle);
        book.setDate(date);
        book.setAuthor(author);
        book.setCategory(cat);
        book.setEdit(ed);
        book.setLang(lang);
        book.setPages(pags);
        book.setDescription(desc);
        book.setEjemplares(ejem);
        book.setStock(Integer.parseInt(stock));
        book.setAvailable(Integer.parseInt(disp));

        try {
            DAOBooks dao = new DAOBooksImpl();

            if (!isEdition) {
                dao.registrar(book);
            } else {
                dao.modificar(book);
            }

            String successMsg = isEdition ? "modificado" : "registrado";

            javax.swing.JOptionPane.showMessageDialog(this, "Libro " + successMsg + " exitosamente.\n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            titleTxt.setText("");
            dateTxt.setText("");
            authorTxt.setText("");
            catTxt.setText("");
            edTxt.setText("");
            langTxt.setText("");
            pagsTxt.setText("");
            descTxt.setText("");
            stockTxt.setText("");
            dispTxt.setText("");
            ejemTxt.setText("");

            if (!isEdition) {
                titleTxt.setText("");
                dateTxt.setText("");
                authorTxt.setText("");
                catTxt.setText("");
                edTxt.setText("");
                langTxt.setText("");
                pagsTxt.setText("");
                descTxt.setText("");
                stockTxt.setText("");
                dispTxt.setText("");
                ejemTxt.setText("");
            }
        } catch (Exception e) {
            String errorMsg = isEdition ? "modificar" : "registrar";
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al " + errorMsg + " el libro. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.components.PanelRound Text;
    private javax.swing.JLabel Welcome;
    private com.mycompany.components.RoundedTextField authorTxt;
    private javax.swing.JPanel bg;
    private com.mycompany.components.ButtonUse button;
    private com.mycompany.components.RoundedTextField catTxt;
    private com.mycompany.components.RoundedTextField dateTxt;
    private com.mycompany.components.RoundedTextField descTxt;
    private com.mycompany.components.RoundedTextField dispTxt;
    private com.mycompany.components.RoundedTextField edTxt;
    private com.mycompany.components.RoundedTextField ejemTxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private com.mycompany.components.RoundedTextField langTxt;
    private com.mycompany.components.RoundedTextField pagsTxt;
    private com.mycompany.components.RoundedTextField stockTxt;
    private com.mycompany.components.RoundedTextField titleTxt;
    // End of variables declaration//GEN-END:variables
}
