/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.pei.sbibliotecario.DAOusersImpl;
import com.mycompany.interfaces.DAOUsers;
import com.mycompany.utils.SendEmail;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.mail.PasswordAuthentication;
import java.util.Properties;
import javax.mail.Authenticator;
import javax.swing.JTextField;

/**
 *
 * @author Rawad
 */
public class UpUsers extends javax.swing.JPanel {

    boolean isEdition = false;
    com.mycompany.models.Users userEdition;

    public UpUsers() {
        initComponents();
        InitStyles();
    }

    public UpUsers(com.mycompany.models.Users user) {
        initComponents();
        isEdition = true;
        userEdition = user;
        InitStyles();
    }

    private void InitStyles() {
        nameTxt.putClientProperty("JTextField.placeholderText", "Ingrese el nombre del usuario");
        nameTxt.setPlaceholderColor(new Color(183, 183, 183));

        apPTxt.putClientProperty("JTextField.placeholderText", "Ingrese el apellido del usuario");
        apPTxt.setPlaceholderColor(new Color(183, 183, 183));

        apMTxt.putClientProperty("JTextField.placeholderText", "Ingrese el apellido del usuario");
        apMTxt.setPlaceholderColor(new Color(183, 183, 183));

        emailTxt.putClientProperty("JTextField.placeholderText", "Ingrese el email del usuario");
        emailTxt.setPlaceholderColor(new Color(183, 183, 183));

        domTxt.putClientProperty("JTextField.placeholderText", "Ingrese el domicilio del usuario");
        domTxt.setPlaceholderColor(new Color(183, 183, 183));

        phoneTxt.putClientProperty("JTextField.placeholderText", "Ingrese el telefono del usuario");
        phoneTxt.setPlaceholderColor(new Color(183, 183, 183));

        if (isEdition) {
            Welcome.setText("Editar Usuario");
            button.setText("Editar");

            if (userEdition != null) {
                nameTxt.setText(userEdition.getName());
                apPTxt.setText(userEdition.getLast_name_p());
                apMTxt.setText(userEdition.getLast_name_m());
                domTxt.setText(userEdition.getDomicilio());
                phoneTxt.setText(userEdition.getTel());
                emailTxt.setText(userEdition.getEmail());
            }
        }

        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                requestFocus(); // Fuerza el foco al frame principal
            }
        });

    }

    ;
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        Text = new com.mycompany.components.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        apPTxt = new com.mycompany.components.RoundedTextField();
        button = new com.mycompany.components.ButtonUse();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        nameTxt = new com.mycompany.components.RoundedTextField();
        apMTxt = new com.mycompany.components.RoundedTextField();
        emailTxt = new com.mycompany.components.RoundedTextField();
        domTxt = new com.mycompany.components.RoundedTextField();
        phoneTxt = new com.mycompany.components.RoundedTextField();

        setBackground(new Color(0,0,0,0));
        setMinimumSize(new java.awt.Dimension(774, 612));
        setPreferredSize(new java.awt.Dimension(774, 612));

        bg.setBackground(new java.awt.Color(255, 255, 255,0));
        bg.setMinimumSize(new java.awt.Dimension(774, 612));
        bg.setPreferredSize(new java.awt.Dimension(774, 612));

        Welcome.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        Welcome.setForeground(new java.awt.Color(30, 30, 30));
        Welcome.setText("Agregar Usuario");

        Text.setBackground(new java.awt.Color(249, 249, 249));
        Text.setForeground(new java.awt.Color(10, 10, 10));
        Text.setRoundBottomLeft(35);
        Text.setRoundBottomRight(35);
        Text.setRoundTopLeft(35);
        Text.setRoundTopRight(35);

        jLabel2.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(10, 10, 10));
        jLabel2.setText("Nombre");

        apPTxt.setBackground(new Color(255,255,255,0));
        apPTxt.setForeground(new java.awt.Color(10, 10, 10));
        apPTxt.setBorderRadius(25);
        apPTxt.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        apPTxt.setMinimumSize(new java.awt.Dimension(280, 30));
        apPTxt.setPreferredSize(new java.awt.Dimension(280, 30));

        button.setForeground(new java.awt.Color(253, 253, 253));
        button.setText("Registrar");
        button.setColorClick(new java.awt.Color(42, 42, 42));
        button.setColorOver(new java.awt.Color(42, 42, 42));
        button.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        button.setRadius(40);
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(10, 10, 10));
        jLabel4.setText("Apellido Paterno");

        jLabel5.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(10, 10, 10));
        jLabel5.setText("Apellido Materno");

        jLabel6.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(10, 10, 10));
        jLabel6.setText("Domicilio");

        jLabel7.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(10, 10, 10));
        jLabel7.setText("Telefono");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));

        jLabel3.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(10, 10, 10));
        jLabel3.setText("Email");

        nameTxt.setBackground(new Color(255,255,255,0));
        nameTxt.setForeground(new java.awt.Color(10, 10, 10));
        nameTxt.setBorderRadius(25);
        nameTxt.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        nameTxt.setMinimumSize(new java.awt.Dimension(280, 30));
        nameTxt.setPreferredSize(new java.awt.Dimension(280, 30));

        apMTxt.setBackground(new Color(255,255,255,0));
        apMTxt.setForeground(new java.awt.Color(10, 10, 10));
        apMTxt.setBorderRadius(25);
        apMTxt.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        apMTxt.setMinimumSize(new java.awt.Dimension(280, 30));
        apMTxt.setPreferredSize(new java.awt.Dimension(280, 30));

        emailTxt.setBackground(new Color(255,255,255,0));
        emailTxt.setForeground(new java.awt.Color(10, 10, 10));
        emailTxt.setBorderRadius(25);
        emailTxt.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        emailTxt.setMinimumSize(new java.awt.Dimension(280, 30));
        emailTxt.setPreferredSize(new java.awt.Dimension(280, 30));

        domTxt.setBackground(new Color(255,255,255,0));
        domTxt.setForeground(new java.awt.Color(10, 10, 10));
        domTxt.setBorderRadius(25);
        domTxt.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        domTxt.setMinimumSize(new java.awt.Dimension(280, 30));
        domTxt.setPreferredSize(new java.awt.Dimension(280, 30));

        phoneTxt.setBackground(new Color(255,255,255,0));
        phoneTxt.setForeground(new java.awt.Color(10, 10, 10));
        phoneTxt.setBorderRadius(25);
        phoneTxt.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        phoneTxt.setMinimumSize(new java.awt.Dimension(280, 30));
        phoneTxt.setPreferredSize(new java.awt.Dimension(280, 30));

        javax.swing.GroupLayout TextLayout = new javax.swing.GroupLayout(Text);
        Text.setLayout(TextLayout);
        TextLayout.setHorizontalGroup(
            TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextLayout.createSequentialGroup()
                .addGroup(TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TextLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TextLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(TextLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(2, 2, 2))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TextLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(apMTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(apPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addGroup(TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TextLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(TextLayout.createSequentialGroup()
                                .addGroup(TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(domTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                    .addComponent(phoneTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(24, 24, 24))
        );
        TextLayout.setVerticalGroup(
            TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TextLayout.createSequentialGroup()
                        .addGroup(TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(TextLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(domTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(112, 112, 112)
                        .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(TextLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apMTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206))))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(68, 68, 68))
                    .addComponent(Text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed

        String nombre = nameTxt.getText();
        String apP = apPTxt.getText();
        String apM = apMTxt.getText();
        String dom = domTxt.getText();
        String tel = phoneTxt.getText();
        String email = emailTxt.getText();

        if (nombre.isEmpty() || apP.isEmpty() || apM.isEmpty() || dom.isEmpty() || tel.isEmpty() || email.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            nameTxt.requestFocus();
            return;
        }

        com.mycompany.models.Users user = isEdition ? userEdition : new com.mycompany.models.Users();
        user.setName(nombre);
        user.setLast_name_p(apP);
        user.setLast_name_m(apM);
        user.setEmail(email);
        user.setDomicilio(dom);
        user.setTel(tel);

        try {
            DAOUsers dao = new DAOusersImpl();

            if (!isEdition) {
                dao.registrar(user);

                SendEmail enviarCorreo = new SendEmail();
                String emailDestino = email; 
                String nombreUsuario = nombre+" "+apP+" "+apM;

                String asunto = "¡Bienvenido a Bookly - Tu registro fue exitoso!";

                String contenidoHTML = "<!DOCTYPE html>"
                        + "<html>"
                        + "<head>"
                        + "   <style>"
                        + "       body { font-family: Arial, sans-serif; }"
                        + "       .container { max-width: 600px; margin: auto; padding: 20px; }"
                        + "       .header { background-color: #4285F4; color: white; padding: 10px; text-align: center; }"
                        + "       .button { background-color: #4285F4; color: white; padding: 10px 20px; text-decoration: none; }"
                        + "   </style>"
                        + "</head>"
                        + "<body>"
                        + "   <div class='container'>"
                        + "       <div class='header'>"
                        + "           <h1>Bookly</h1>"
                        + "       </div>"
                        + "       <h2>¡Hola, " + nombreUsuario + "!</h2>"
                        + "       <p>Tu registro en Bookly se completó exitosamente.</p>"
                        + "       <p>Gracias por unirte a nuestra comunidad de lectores.</p>"
                        + "   </div>"
                        + "</body>"
                        + "</html>";

                try {
                    enviarCorreo.enviarCorreo(emailDestino, asunto, contenidoHTML);
                    System.out.println("Correo de registro enviado exitosamente");
                } catch (Exception e) {
                    System.out.println(e);
                }
            } else {
                dao.modificar(user);
            }

            String successMsg = isEdition ? "modificado" : "registrado";

            javax.swing.JOptionPane.showMessageDialog(this, "Usuario " + successMsg + " exitosamente.\n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            nameTxt.setText("");
            apPTxt.setText("");
            apMTxt.setText("");
            domTxt.setText("");
            phoneTxt.setText("");
            emailTxt.setText("");

            if (!isEdition) {
                nameTxt.setText("");
                apPTxt.setText("");
                apMTxt.setText("");
                domTxt.setText("");
                phoneTxt.setText("");
                emailTxt.setText("");
            }
        } catch (Exception e) {
            String errorMsg = isEdition ? "modificar" : "registrar";
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al " + errorMsg + " el usuario. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.components.PanelRound Text;
    private javax.swing.JLabel Welcome;
    private com.mycompany.components.RoundedTextField apMTxt;
    private com.mycompany.components.RoundedTextField apPTxt;
    private javax.swing.JPanel bg;
    private com.mycompany.components.ButtonUse button;
    private com.mycompany.components.RoundedTextField domTxt;
    private com.mycompany.components.RoundedTextField emailTxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private com.mycompany.components.RoundedTextField nameTxt;
    private com.mycompany.components.RoundedTextField phoneTxt;
    // End of variables declaration//GEN-END:variables
}
