/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.interfaces.DAOUsers;
import com.mycompany.pei.sbibliotecario.DAOusersImpl;
import com.mycompany.pei.sbibliotecario.Dashboard;
import com.mycompany.utils.SendEmail;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Rawad
 */
public class Users extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Users() {
        initComponents();
        LoadUsers();

        userSearch.putClientProperty("JTextField.placeholderText", "Ingrese el nombre del usuario");
        userSearch.setPlaceholderColor(new Color(183, 183, 183));

        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                requestFocus(); // Fuerza el foco al frame principal
            }
        });

        jTable1.setFont(new Font("Inter", Font.PLAIN, 11));

        JTableHeader header = jTable1.getTableHeader();
        header.setFont(new Font("Inter", Font.PLAIN, 11));
    }

    private void LoadUsers() {
        try {
            DAOUsers dao = new DAOusersImpl();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            dao.listar("").forEach((u) -> model.addRow(new Object[]{u.getId(), u.getName(), u.getLast_name_p(), u.getLast_name_m(), u.getDomicilio(), u.getTel(), u.getEmail()}));
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Functions = new javax.swing.JPanel();
        searchButton = new com.mycompany.components.ButtonUse();
        userSearch = new com.mycompany.components.RoundedTextField();
        addButton = new com.mycompany.components.ButtonUse();
        deleteButton = new com.mycompany.components.ButtonUse();
        editButton = new com.mycompany.components.ButtonUse();

        setBackground(new Color(0,0,0,0));
        setMinimumSize(new java.awt.Dimension(774, 612));
        setPreferredSize(new java.awt.Dimension(774, 612));

        bg.setBackground(new java.awt.Color(255, 255, 255,0));
        bg.setMinimumSize(new java.awt.Dimension(774, 612));
        bg.setPreferredSize(new java.awt.Dimension(774, 612));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Welcome.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        Welcome.setForeground(new java.awt.Color(30, 30, 30));
        Welcome.setText("Usuarios");
        bg.add(Welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 33, 575, 42));

        jScrollPane1.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N

        jTable1.setFont(new java.awt.Font("Inter", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido P.", "Apellido M.", "Domicilio", "Teléfono", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setRowHeight(30);
        jTable1.setSelectionBackground(new java.awt.Color(51, 51, 51));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 215, 740, 320));

        Functions.setBackground(new java.awt.Color(255, 255, 255));

        searchButton.setForeground(new java.awt.Color(253, 253, 253));
        searchButton.setText("Buscar");
        searchButton.setColorClick(new java.awt.Color(42, 42, 42));
        searchButton.setColorOver(new java.awt.Color(42, 42, 42));
        searchButton.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        searchButton.setMaximumSize(new java.awt.Dimension(148, 45));
        searchButton.setMinimumSize(new java.awt.Dimension(148, 45));
        searchButton.setPreferredSize(new java.awt.Dimension(148, 45));
        searchButton.setRadius(40);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        userSearch.setBackground(new Color(255,255,255,0));
        userSearch.setForeground(new java.awt.Color(10, 10, 10));
        userSearch.setBorderRadius(40);
        userSearch.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        userSearch.setMinimumSize(new java.awt.Dimension(645, 45));
        userSearch.setPreferredSize(new java.awt.Dimension(645, 45));

        javax.swing.GroupLayout FunctionsLayout = new javax.swing.GroupLayout(Functions);
        Functions.setLayout(FunctionsLayout);
        FunctionsLayout.setHorizontalGroup(
            FunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FunctionsLayout.createSequentialGroup()
                .addComponent(userSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FunctionsLayout.setVerticalGroup(
            FunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FunctionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bg.add(Functions, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 149, 740, 60));

        addButton.setForeground(new java.awt.Color(253, 253, 253));
        addButton.setText("Nuevo");
        addButton.setColorClick(new java.awt.Color(42, 42, 42));
        addButton.setColorOver(new java.awt.Color(42, 42, 42));
        addButton.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        addButton.setMaximumSize(new java.awt.Dimension(148, 45));
        addButton.setMinimumSize(new java.awt.Dimension(148, 45));
        addButton.setPreferredSize(new java.awt.Dimension(148, 45));
        addButton.setRadius(40);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        bg.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 148, 45));

        deleteButton.setForeground(new java.awt.Color(253, 253, 253));
        deleteButton.setText("Borrar");
        deleteButton.setColorClick(new java.awt.Color(42, 42, 42));
        deleteButton.setColorOver(new java.awt.Color(42, 42, 42));
        deleteButton.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        deleteButton.setMaximumSize(new java.awt.Dimension(148, 45));
        deleteButton.setMinimumSize(new java.awt.Dimension(148, 45));
        deleteButton.setPreferredSize(new java.awt.Dimension(148, 45));
        deleteButton.setRadius(40);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        bg.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, 148, 45));

        editButton.setForeground(new java.awt.Color(253, 253, 253));
        editButton.setText("Editar");
        editButton.setColorClick(new java.awt.Color(42, 42, 42));
        editButton.setColorOver(new java.awt.Color(42, 42, 42));
        editButton.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        editButton.setMaximumSize(new java.awt.Dimension(148, 45));
        editButton.setMinimumSize(new java.awt.Dimension(148, 45));
        editButton.setPreferredSize(new java.awt.Dimension(148, 45));
        editButton.setRadius(40);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        bg.add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, 148, 45));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed

    }//GEN-LAST:event_jTable1MousePressed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        try {

            if (userSearch.getText().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Debes ingresar el nombre del usuario a buscar.\n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            }

            DAOUsers dao = new DAOusersImpl();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            dao.listar(userSearch.getText()).forEach((u) -> model.addRow(new Object[]{u.getId(), u.getName(), u.getLast_name_p(), u.getLast_name_m(), u.getDomicilio(), u.getTel(), u.getEmail()}));
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        Dashboard.ShowJPanel(new UpUsers());
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed

        DAOUsers dao = new DAOusersImpl();

        if (jTable1.getSelectedRows().length < 1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debes seleccionar uno o más usuarios a eliminar.\n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
        } else {
            for (int i : jTable1.getSelectedRows()) {
                try {

                    com.mycompany.models.Users currentUser = dao.getUserById((int) jTable1.getValueAt(i, 0));

                    int respuesta = javax.swing.JOptionPane.showConfirmDialog(
                            this,
                            "<html><body><p style='width: 200px;'>¿Estás seguro de eliminar permanentemente al usuario seleccionado?<br><b>Esta acción no puede revertirse.</b></p></body></html>",
                            "Confirmar eliminación",
                            javax.swing.JOptionPane.YES_NO_OPTION,
                            javax.swing.JOptionPane.WARNING_MESSAGE
                    );

                    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
                        SendEmail enviarCorreo = new SendEmail();
                        String name = currentUser.getName();
                        String lnameP = currentUser.getLast_name_p();
                        String lnameM = currentUser.getLast_name_m();
                        String email = currentUser.getEmail();
                        String nombreUsuario = name + " " + lnameP + " " + lnameM;
                        dao.eliminar((int) jTable1.getValueAt(i, 0));
                        LoadUsers();
                        System.out.println("ID A ELEMININAR=" + (int) jTable1.getValueAt(i, 0));
                        String asunto = "Tu cuenta en Bookly ha sido eliminada";

                        String contenidoHTML = String.format("""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <style>
                body { font-family: 'Segoe UI', Arial, sans-serif; line-height: 1.6; color: #333; }
                .container { max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px; }
                .header { background-color: #E53935; padding: 20px; text-align: center; border-radius: 8px 8px 0 0; }
                .header h1 { color: white; margin: 0; }
                .content { padding: 20px; }
                .highlight-box { 
                    background: #FFEBEE; 
                    padding: 15px; 
                    border-left: 4px solid #E53935;
                    margin: 20px 0;
                }
                .footer { 
                    margin-top: 20px; 
                    padding-top: 20px; 
                    border-top: 1px solid #e0e0e0; 
                    font-size: 12px; 
                    color: #777; 
                }
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>Bookly</h1>
                </div>
                <div class="content">
                    <h2>Hola, %s</h2>
                    
                    <div class="highlight-box">
                        <h3 style="margin-top: 0; color: #E53935;">Tu cuenta ha sido eliminada</h3>
                        <p>Todos tus datos personales han sido eliminados permanentemente de nuestro sistema.</p>
                    </div>
                    
                    <p><strong>Detalles importantes:</strong></p>
                    <ul>
                        <li>Ya no podrás acceder al sistema con estas credenciales</li>
                        <li>Tus préstamos activos han sido cancelados</li>
                        <li>No recibirás más comunicaciones de nuestra parte</li>
                    </ul>
                    
                    <p>Si esto fue un error o necesitas ayuda, contáctanos respondiendo a este correo.</p>
                    
                    <p>Gracias por haber sido parte de nuestra comunidad de lectores.</p>
                </div>
                <div class="footer">
                    <p>© %d Bookly - Sistema de Gestión de Bibliotecas</p>
                    <p>Este es un correo automático, por favor no lo respondas directamente.</p>
                </div>
            </div>
        </body>
        </html>
        """,
                                nombreUsuario,
                                java.time.Year.now().getValue());

                        try {
                            enviarCorreo.enviarCorreo(email, asunto, contenidoHTML);
                            System.out.println("Correo de registro enviado exitosamente");
                        } catch (Exception e) {
                            System.out.println(e);
                        }

                    }

                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        if (jTable1.getSelectedRow() > -1) {
            try {
                int userId = (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
                DAOUsers dao = new DAOusersImpl();
                Dashboard.ShowJPanel(new UpUsers(dao.getUserById(userId)));
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Debes seleccionar el usuario a editar.\n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Functions;
    private javax.swing.JLabel Welcome;
    private com.mycompany.components.ButtonUse addButton;
    private javax.swing.JPanel bg;
    private com.mycompany.components.ButtonUse deleteButton;
    private com.mycompany.components.ButtonUse editButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.mycompany.components.ButtonUse searchButton;
    private com.mycompany.components.RoundedTextField userSearch;
    // End of variables declaration//GEN-END:variables
}
